


# Site settings

email: your-email@domain.com
url: https://example.github.io
welcome: Welcome to the Inflo Project
skills: 


title: The Inflo Project
description: a new, revolutionary way to share and access the content that matters to you

keywords: "your keywords, separated by commas"
meta_author: Sukiennik Nicholas

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
#contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  white: 999
  primary: 1494C2 #18bc9c #80B3FF //green
  primary-rgb: "24,288,156" #"128,179,255"
  secondary: 2C3E65 # #FD6E8A
  secondary-dark: 233155 #233140 #A2122F dark blue
  twitty: e7ecf1 #bg gray

# Footer settings
footer:
  copyright: The Inflo Project
  location: World
  social: Connect with us
  credits: About

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/infloproject
 # - title: medium
  #  url: https://medium.com/the-inflo-project/


# Postal address (add as many lines as necessary)
address:
  - line: 
  - line: 

# Credits content
credits: 'The Inflo Project is a next generation content sharing 
platform revising the way we access and share information on the web, <i>intended to nourish, not feed.</i>'

# Build settings
markdown: kramdown
permalink: pretty
